[phases.setup]
nixPkgs = ["python3", "chromium", "nss", "nspr", "atk", "cups", "drm", "xkbcommon", "composite", "damage", "fixes", "randr", "gbm", "alsaLib"]
[phases.build]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]
